// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: dkvs/partition/rpc.proto

package partition

import (
	prototypes "github.com/pysel/dkvs/prototypes"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareCommitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*PrepareCommitRequest_Set
	//	*PrepareCommitRequest_Delete
	Message isPrepareCommitRequest_Message `protobuf_oneof:"message"`
}

func (x *PrepareCommitRequest) Reset() {
	*x = PrepareCommitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkvs_partition_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareCommitRequest) ProtoMessage() {}

func (x *PrepareCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkvs_partition_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareCommitRequest.ProtoReflect.Descriptor instead.
func (*PrepareCommitRequest) Descriptor() ([]byte, []int) {
	return file_dkvs_partition_rpc_proto_rawDescGZIP(), []int{0}
}

func (m *PrepareCommitRequest) GetMessage() isPrepareCommitRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *PrepareCommitRequest) GetSet() *prototypes.SetRequest {
	if x, ok := x.GetMessage().(*PrepareCommitRequest_Set); ok {
		return x.Set
	}
	return nil
}

func (x *PrepareCommitRequest) GetDelete() *prototypes.DeleteRequest {
	if x, ok := x.GetMessage().(*PrepareCommitRequest_Delete); ok {
		return x.Delete
	}
	return nil
}

type isPrepareCommitRequest_Message interface {
	isPrepareCommitRequest_Message()
}

type PrepareCommitRequest_Set struct {
	Set *prototypes.SetRequest `protobuf:"bytes,1,opt,name=set,proto3,oneof"`
}

type PrepareCommitRequest_Delete struct {
	Delete *prototypes.DeleteRequest `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

func (*PrepareCommitRequest_Set) isPrepareCommitRequest_Message() {}

func (*PrepareCommitRequest_Delete) isPrepareCommitRequest_Message() {}

type PrepareCommitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *PrepareCommitResponse) Reset() {
	*x = PrepareCommitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkvs_partition_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareCommitResponse) ProtoMessage() {}

func (x *PrepareCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkvs_partition_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareCommitResponse.ProtoReflect.Descriptor instead.
func (*PrepareCommitResponse) Descriptor() ([]byte, []int) {
	return file_dkvs_partition_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareCommitResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type AbortCommitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AbortCommitRequest) Reset() {
	*x = AbortCommitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkvs_partition_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbortCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortCommitRequest) ProtoMessage() {}

func (x *AbortCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkvs_partition_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortCommitRequest.ProtoReflect.Descriptor instead.
func (*AbortCommitRequest) Descriptor() ([]byte, []int) {
	return file_dkvs_partition_rpc_proto_rawDescGZIP(), []int{2}
}

type AbortCommitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AbortCommitResponse) Reset() {
	*x = AbortCommitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkvs_partition_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbortCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortCommitResponse) ProtoMessage() {}

func (x *AbortCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkvs_partition_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortCommitResponse.ProtoReflect.Descriptor instead.
func (*AbortCommitResponse) Descriptor() ([]byte, []int) {
	return file_dkvs_partition_rpc_proto_rawDescGZIP(), []int{3}
}

type CommitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkvs_partition_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkvs_partition_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_dkvs_partition_rpc_proto_rawDescGZIP(), []int{4}
}

type CommitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkvs_partition_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkvs_partition_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_dkvs_partition_rpc_proto_rawDescGZIP(), []int{5}
}

var File_dkvs_partition_rpc_proto protoreflect.FileDescriptor

var file_dkvs_partition_rpc_proto_rawDesc = []byte{
	0x0a, 0x18, 0x64, 0x6b, 0x76, 0x73, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x64, 0x6b, 0x76, 0x73,
	0x2e, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1a, 0x64, 0x6b, 0x76, 0x73,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x01, 0x0a, 0x14, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x72, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2c, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64,
	0x6b, 0x76, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x03, 0x73, 0x65, 0x74, 0x12, 0x35, 0x0a,
	0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x64, 0x6b, 0x76, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x27, 0x0a, 0x15, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x14, 0x0a, 0x12, 0x41, 0x62, 0x6f, 0x72,
	0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15,
	0x0a, 0x13, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa5, 0x04, 0x0a, 0x10, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a,
	0x03, 0x53, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x64, 0x6b, 0x76, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x64, 0x6b, 0x76, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x03, 0x47, 0x65, 0x74,
	0x12, 0x18, 0x2e, 0x64, 0x6b, 0x76, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x64, 0x6b, 0x76,
	0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x1b, 0x2e, 0x64, 0x6b, 0x76, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x64,
	0x6b, 0x76, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0d, 0x50, 0x72,
	0x65, 0x70, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x24, 0x2e, 0x64, 0x6b,
	0x76, 0x73, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x64, 0x6b, 0x76, 0x73, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0b, 0x41, 0x62, 0x6f, 0x72,
	0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x22, 0x2e, 0x64, 0x6b, 0x76, 0x73, 0x2e, 0x70,
	0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x6b,
	0x76, 0x73, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x62, 0x6f,
	0x72, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x47, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x1d, 0x2e, 0x64, 0x6b, 0x76,
	0x73, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x6b, 0x76, 0x73,
	0x2e, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0c, 0x53, 0x65, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x21, 0x2e, 0x64, 0x6b, 0x76, 0x73,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x64,
	0x6b, 0x76, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x48,
	0x61, 0x73, 0x68, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x79, 0x73, 0x65, 0x6c, 0x2f, 0x64, 0x6b, 0x76, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dkvs_partition_rpc_proto_rawDescOnce sync.Once
	file_dkvs_partition_rpc_proto_rawDescData = file_dkvs_partition_rpc_proto_rawDesc
)

func file_dkvs_partition_rpc_proto_rawDescGZIP() []byte {
	file_dkvs_partition_rpc_proto_rawDescOnce.Do(func() {
		file_dkvs_partition_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_dkvs_partition_rpc_proto_rawDescData)
	})
	return file_dkvs_partition_rpc_proto_rawDescData
}

var file_dkvs_partition_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dkvs_partition_rpc_proto_goTypes = []interface{}{
	(*PrepareCommitRequest)(nil),            // 0: dkvs.partition.PrepareCommitRequest
	(*PrepareCommitResponse)(nil),           // 1: dkvs.partition.PrepareCommitResponse
	(*AbortCommitRequest)(nil),              // 2: dkvs.partition.AbortCommitRequest
	(*AbortCommitResponse)(nil),             // 3: dkvs.partition.AbortCommitResponse
	(*CommitRequest)(nil),                   // 4: dkvs.partition.CommitRequest
	(*CommitResponse)(nil),                  // 5: dkvs.partition.CommitResponse
	(*prototypes.SetRequest)(nil),           // 6: dkvs.message.SetRequest
	(*prototypes.DeleteRequest)(nil),        // 7: dkvs.message.DeleteRequest
	(*prototypes.GetRequest)(nil),           // 8: dkvs.message.GetRequest
	(*prototypes.SetHashrangeRequest)(nil),  // 9: dkvs.message.SetHashrangeRequest
	(*prototypes.SetResponse)(nil),          // 10: dkvs.message.SetResponse
	(*prototypes.GetResponse)(nil),          // 11: dkvs.message.GetResponse
	(*prototypes.DeleteResponse)(nil),       // 12: dkvs.message.DeleteResponse
	(*prototypes.SetHashrangeResponse)(nil), // 13: dkvs.message.SetHashrangeResponse
}
var file_dkvs_partition_rpc_proto_depIdxs = []int32{
	6,  // 0: dkvs.partition.PrepareCommitRequest.set:type_name -> dkvs.message.SetRequest
	7,  // 1: dkvs.partition.PrepareCommitRequest.delete:type_name -> dkvs.message.DeleteRequest
	6,  // 2: dkvs.partition.PartitionService.Set:input_type -> dkvs.message.SetRequest
	8,  // 3: dkvs.partition.PartitionService.Get:input_type -> dkvs.message.GetRequest
	7,  // 4: dkvs.partition.PartitionService.Delete:input_type -> dkvs.message.DeleteRequest
	0,  // 5: dkvs.partition.PartitionService.PrepareCommit:input_type -> dkvs.partition.PrepareCommitRequest
	2,  // 6: dkvs.partition.PartitionService.AbortCommit:input_type -> dkvs.partition.AbortCommitRequest
	4,  // 7: dkvs.partition.PartitionService.Commit:input_type -> dkvs.partition.CommitRequest
	9,  // 8: dkvs.partition.PartitionService.SetHashrange:input_type -> dkvs.message.SetHashrangeRequest
	10, // 9: dkvs.partition.PartitionService.Set:output_type -> dkvs.message.SetResponse
	11, // 10: dkvs.partition.PartitionService.Get:output_type -> dkvs.message.GetResponse
	12, // 11: dkvs.partition.PartitionService.Delete:output_type -> dkvs.message.DeleteResponse
	1,  // 12: dkvs.partition.PartitionService.PrepareCommit:output_type -> dkvs.partition.PrepareCommitResponse
	3,  // 13: dkvs.partition.PartitionService.AbortCommit:output_type -> dkvs.partition.AbortCommitResponse
	5,  // 14: dkvs.partition.PartitionService.Commit:output_type -> dkvs.partition.CommitResponse
	13, // 15: dkvs.partition.PartitionService.SetHashrange:output_type -> dkvs.message.SetHashrangeResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_dkvs_partition_rpc_proto_init() }
func file_dkvs_partition_rpc_proto_init() {
	if File_dkvs_partition_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dkvs_partition_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareCommitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dkvs_partition_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareCommitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dkvs_partition_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbortCommitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dkvs_partition_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbortCommitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dkvs_partition_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dkvs_partition_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dkvs_partition_rpc_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PrepareCommitRequest_Set)(nil),
		(*PrepareCommitRequest_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dkvs_partition_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dkvs_partition_rpc_proto_goTypes,
		DependencyIndexes: file_dkvs_partition_rpc_proto_depIdxs,
		MessageInfos:      file_dkvs_partition_rpc_proto_msgTypes,
	}.Build()
	File_dkvs_partition_rpc_proto = out.File
	file_dkvs_partition_rpc_proto_rawDesc = nil
	file_dkvs_partition_rpc_proto_goTypes = nil
	file_dkvs_partition_rpc_proto_depIdxs = nil
}
