// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: dkvs/balancer/rpc.proto

package balancer

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on RegisterPartitionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterPartitionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterPartitionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterPartitionRequestMultiError, or nil if none found.
func (m *RegisterPartitionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterPartitionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Address

	if len(errors) > 0 {
		return RegisterPartitionRequestMultiError(errors)
	}

	return nil
}

// RegisterPartitionRequestMultiError is an error wrapping multiple validation
// errors returned by RegisterPartitionRequest.ValidateAll() if the designated
// constraints aren't met.
type RegisterPartitionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterPartitionRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterPartitionRequestMultiError) AllErrors() []error { return m }

// RegisterPartitionRequestValidationError is the validation error returned by
// RegisterPartitionRequest.Validate if the designated constraints aren't met.
type RegisterPartitionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterPartitionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterPartitionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterPartitionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterPartitionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterPartitionRequestValidationError) ErrorName() string {
	return "RegisterPartitionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterPartitionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterPartitionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterPartitionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterPartitionRequestValidationError{}

// Validate checks the field values on RegisterPartitionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterPartitionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterPartitionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterPartitionResponseMultiError, or nil if none found.
func (m *RegisterPartitionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterPartitionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RegisterPartitionResponseMultiError(errors)
	}

	return nil
}

// RegisterPartitionResponseMultiError is an error wrapping multiple validation
// errors returned by RegisterPartitionResponse.ValidateAll() if the
// designated constraints aren't met.
type RegisterPartitionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterPartitionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterPartitionResponseMultiError) AllErrors() []error { return m }

// RegisterPartitionResponseValidationError is the validation error returned by
// RegisterPartitionResponse.Validate if the designated constraints aren't met.
type RegisterPartitionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterPartitionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterPartitionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterPartitionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterPartitionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterPartitionResponseValidationError) ErrorName() string {
	return "RegisterPartitionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterPartitionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterPartitionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterPartitionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterPartitionResponseValidationError{}

// Validate checks the field values on GetIdRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetIdRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIdRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetIdRequestMultiError, or
// nil if none found.
func (m *GetIdRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIdRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetIdRequestMultiError(errors)
	}

	return nil
}

// GetIdRequestMultiError is an error wrapping multiple validation errors
// returned by GetIdRequest.ValidateAll() if the designated constraints aren't met.
type GetIdRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIdRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIdRequestMultiError) AllErrors() []error { return m }

// GetIdRequestValidationError is the validation error returned by
// GetIdRequest.Validate if the designated constraints aren't met.
type GetIdRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIdRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIdRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIdRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIdRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIdRequestValidationError) ErrorName() string { return "GetIdRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetIdRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIdRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIdRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIdRequestValidationError{}

// Validate checks the field values on GetIdResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetIdResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIdResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetIdResponseMultiError, or
// nil if none found.
func (m *GetIdResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIdResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetIdResponseMultiError(errors)
	}

	return nil
}

// GetIdResponseMultiError is an error wrapping multiple validation errors
// returned by GetIdResponse.ValidateAll() if the designated constraints
// aren't met.
type GetIdResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIdResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIdResponseMultiError) AllErrors() []error { return m }

// GetIdResponseValidationError is the validation error returned by
// GetIdResponse.Validate if the designated constraints aren't met.
type GetIdResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIdResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIdResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIdResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIdResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIdResponseValidationError) ErrorName() string { return "GetIdResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetIdResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIdResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIdResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIdResponseValidationError{}
