name: Scheduled Unit Tests

on:
  schedule:
    - cron: '0 10 1,15 * *' # Run on 1st and 15th days of every month at 10:00 UTC

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: make unit
